name:                buttplug-hs-core
version:             0.1.0.0
github:              "sullyj3/buttplug-hs-core"
license:             BSD3
author:              "James Sully"
maintainer:          "sullyj3@gmail.com"
copyright:           "2020-2021 James Sully"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Library for writing clients for the Buttplug Intimate Device Control Standard. (<https://buttplug.io/>)


dependencies:
- base >= 4.7 && < 5
- bytestring
- aeson
- aeson-casing
- async
- connection
- network
- text
- containers
- unordered-containers
- websockets
- wuss

library:
  source-dirs: src

executables:
  buttplug-hs-core-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - buttplug-hs-core
    # example-1:
    #   main: example1.hs
    #   source-dirs: examples
    # example-2:
    #   main: example2.hs
    #   source-dirs: examples

tests:
  buttplug-hs-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - buttplug-hs-core
    - aeson-pretty
    - QuickCheck
    - quickcheck-instances
    - generic-random
    - raw-strings-qq
