name:                buttplug-hs
version:             0.1.0.0
github:              "sullyj3/buttplug-hs"
license:             BSD3
author:              "James Sully"
maintainer:          "sullyj3@gmail.com"
copyright:           "2020 James Sully"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sullyj3/buttplug-hs#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-casing
- async
- bytestring
- hspec
- mtl
- network
- text
- transformers
- containers
- unordered-containers
- unliftio
- websockets

library:
  source-dirs: src

executables:
  buttplug-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - buttplug-hs

tests:
  buttplug-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - buttplug-hs
